from .MinMax import MinMax 
from .MinMax_DP import MinMax_DP
from .MinMax_DP_BinHash import MinMax_DP_BinHash
from .AlphaBeta_DP import AlphaBeta_DP
from .RandomMove import RandomMove 
from .AlphaBeta import AlphaBeta
from .AlphaBeta_DP_BinHash import AlphaBeta_DP_BinHash
from .Greedy import Greedy
from .MyBot import MyBot   